### root
GET http://localhost:7000/v2


### User register
POST localhost:7000/v2/register
Content-Type: application/json

{
  "email" : "ravshan@gmail.com",
  "password" : "test1"
}

### Login
POST localhost:7000/v2/login
Content-Type: application/json

{
  "email" : "rustam@gmail.com",
  "password" : "test1"
}

### Logout
POST localhost:7000/v2/logout
Content-Type: application/json



### Create Event
POST localhost:7000/v2/event
Content-Type: application/json

{
  "event_name" : "Yozda birga kod yozamiz",
  "end_date" : "12-12-1212"
}

### Get all Events
## userning barcha eventlar ro'yxat
## require : user -> _id
GET localhost:7000/v2/event
Content-Type: application/json

### Get Event
## mavjud event haqidagi malumotlar
## require : event -> _id
GET localhost:7000/v2/event/669e2a5cc05cf2796b0c83c9
Content-Type: application/json

### Delete Event
## require : event -> _id
DELETE localhost:7000/v2/event/66966ea48e4440c9c72dc5d0
Content-Type: application/json


### Update Event
## require : event -> _id
PUT localhost:7000/v2/event/669e2a5cc05cf2796b0c83c9
Content-Type: application/json

{
  "event_name" : "Qishda2 birga kod yozamiz"
}