GET http://localhost:7000/v2


### User register
POST localhost:7000/v2/register
Content-Type: application/json

{
  "email" : "test@gmail.com",
  "password" : "test1"
}

### Login
POST localhost:7000/v2/login
Content-Type: application/json

{
  "email" : "test@gmail.com",
  "password" : "test1"
}

### Logout
POST localhost:7000/v2/logout
Content-Type: application/json

### Get user
GET localhost:7000/v2/getuser
Content-Type: application/json

### Event
GET localhost:7000/v2/d/:id
Content-Type: application/json

{
  "event_name" : "Test event",
  "event_desc" : "test description",
  "end_date" : "12-12-1212"
}